services:
  vscoder:
    image: vscoder:latest
    container_name: vscoder
    hostname: vscode-server
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      - TZ=America/New_York
    ports:
      - 8880:8080 # vscoder ui app
      - 2233:22  # ssh to container 
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8083/healthz || exit 1 "
      interval: 5s
      retries: 5
      timeout: 2s
    volumes:
      - ./.config:/home/coder/.config
      - ./logs:/home/coder/.local/share/code-server/coder-logs
      - ./extensions:/home/coder/.local/share/code-server/extensions
      - ./vsix:/home/coder/.local/share/code-server/vsix
      - ./home/dev:/home/coder/host # change  to current user home
    networks:
      - default
networks:
  default :
    name: vscoder-network
    
