version: "3.8"
services:
  vscoder:
    image: amirmoth/vscoder:v1.0.1
    container_name: vscoder
    hostname: vscode-server
    privileged: true
    stdin_open: true
    user: ${UID}:${GID}
    tty: true
    environment:
      - TZ=America/New_York
    volumes:
      - ./data/.config:/home/coder/.config
      - ./data:/home/coder/.local/share/code-server
      - /home/dev:/home/coder
    labels:
      - traefik.enable=true
      - traefik.http.routers.vscoder.rule=Host(`${HOST_NAME}`)
      - traefik.http.routers.vscoder.entrypoints=websecure
      - traefik.http.routers.vscoder.tls=true
      - traefik.http.routers.vscoder.tls.certresolver=letsencrypt
      - traefik.http.services.vscoder.loadbalancer.server.port=8080
    networks:
      - traefik-network
networks:
  traefik-network:
    external: true
