services:
  vscoder:
    image: vscoder:v1.0.0-latest
    container_name: vscoder
    hostname: vscode-server
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      - TZ=America/New_York
    ports:
      - 8080:8080 # vscoder ui app
      - 2233:22 # ssh to container
    healthcheck:
      test: "curl -v http://localhost:8080/healthz || exit 1 "
      interval: 5s
      retries: 5
      timeout: 2s
    volumes:
      - ./.config:/home/coder/.config
      - ./logs:/home/coder/.local/share/code-server/coder-logs
      - ./extensions:/home/coder/.local/share/code-server/extensions
      - ./vsix:/home/coder/.local/share/code-server/vsix
    networks:
      - default
networks:
  default:
    name: vscoder-network
