services:
  vscode-server:
    image: vscode:${TAG:-latest}
    container_name: vscode
    hostname: vscode
    user: ${UID}:${GID}
    stdin_open: true # docker run -i
    tty: true # docker run -t
    ports:
      - 8080:8080
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8083/healthz || exit 1 "
      interval: 5s
      retries: 5
      timeout: 2s
    volumes:
      - $PWD/.config:/home/coder/.config
      - $PWD/.logs:/home/coder/.local/share/code-server/coder-logs
      - $PWD/extensions:/home/coder/.local/share/code-server/extensions
      - $PWD/vsix:/home/coder/.local/share/code-server/vsix
      - $HOME/:/home/coder
    networks:
      - vscode-network
networks:
  vscode-network:
    external: true
