name: Release

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
  push:
    tags:
      - 'v*'  # Trigger only on tag push that matches 'v*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip setuptools wheel poetry

    - name: Determine Tag or Branch
      id: get_ref
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        else
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
        fi

    - name: Build Docker Image
      run: |
        if [ -n "${{ env.TAG_NAME }}" ]; then
          IMAGE_TAG=${{ env.TAG_NAME }}
        else
          IMAGE_TAG=${{ env.BRANCH_NAME }}
        fi
        docker build -t amirtaherkhani/vscoder:$IMAGE_TAG .
        echo "Docker image tag: $IMAGE_TAG"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker push amirtaherkhani/vscoder:${{ env.TAG_NAME || env.BRANCH_NAME }}
