name: Release

on:
  workflow_dispatch:  # Allows manual triggering from the GitHub UI
  push:
    tags:
      - 'v*'  # Trigger only on tag push that matches 'v*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip setuptools wheel poetry

    - name: Extract Tag Name
      id: extract_tag
      run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Build Docker Image
      run: |
        IMAGE_TAG=${{ env.TAG_NAME }}
        docker build -t amirtaherkhani/vscoder:$IMAGE_TAG .
        echo "Docker image tag: $IMAGE_TAG"

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        IMAGE_TAG=$(docker images --filter=reference='amirtaherkhani/vscoder' --format "{{.Tag}}" | head -n 1)
        docker push amirmoth/vscoder:$IMAGE_TAG
