name: Release

on:
  push:
    tags:
      - 'v*' # Trigger only on tag push that matches 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install --upgrade pip setuptools wheel poetry

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACCOUNT_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }} # This refers to the tag name that triggered the workflow
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Build Docker Image
      run: |
        IMAGE_TAG=${{ github.ref_name }}
        docker build -t amirtaherkhani/vscoder:$IMAGE_TAG .
        echo $IMAGE_TAG

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        IMAGE_TAG=${{ github.ref_name }}
        docker push amirtaherkhani/vscoder:$IMAGE_TAG
